name: sliver_tools_example
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  # state management
  provider: ^4.3.2+4

  # more slivers
  sliver_tools: ^0.1.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true